using System.Text.Json.Serialization;

namespace MagicLoaderGenerator.Filesystem;

// ReSharper disable CollectionNeverUpdated.Global
/// <summary>
/// A record used to load the translation keys to be used to generate MagicLoader files.
/// Holds the transformed values generated by the mod to be used in an output generator.
/// </summary>
public record MagicLoaderFile
{
    /// <summary>
    /// A list of translation keys used to generate the fullname edit entries of the mod files
    /// </summary>
    [JsonIgnore] public IList<string> FullNamesEditEntries { get; } = [];
    /// <summary>
    /// A list of translation keys used to generate the fullname entries of the mod files
    /// </summary>
    [JsonIgnore] public IList<string> FullNameEntries { get; } = [];

    // ReSharper disable once InconsistentNaming
    /// <summary>
    /// The fullname edit entries to write to the MagicLoader file
    /// </summary>
    [JsonInclude] public Dictionary<string, string>? FullNames_Edit;
    /// <summary>
    /// The fullname entries to write to the MagicLoader file
    /// </summary>
    [JsonInclude] public Dictionary<string, string>? FullNames;

    /// <summary>
    /// Checks if the MagicLoader file contains any entry
    /// </summary>
    /// <returns><c>true</c> if the file contains at least one entry; <c>false</c> otherwise</returns>
    public bool HasEntries()
    {
        return FullNamesEditEntries.Any() || FullNameEntries.Any();
    }
}
